# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vboxuser/projects/miniRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vboxuser/projects/miniRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vboxuser/projects/miniRT/CMakeFiles /home/vboxuser/projects/miniRT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vboxuser/projects/miniRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named miniRT

# Build rule for target.
miniRT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miniRT
.PHONY : miniRT

# fast build rule for target.
miniRT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/build
.PHONY : miniRT/fast

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) $(MAKESILENT) -f lib/Libft/CMakeFiles/ft.dir/build.make lib/Libft/CMakeFiles/ft.dir/build
.PHONY : ft/fast

#=============================================================================
# Target rules for targets named mlx42

# Build rule for target.
mlx42: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlx42
.PHONY : mlx42

# fast build rule for target.
mlx42/fast:
	$(MAKE) $(MAKESILENT) -f lib/MLX42/CMakeFiles/mlx42.dir/build.make lib/MLX42/CMakeFiles/mlx42.dir/build
.PHONY : mlx42/fast

#=============================================================================
# Target rules for targets named get_next_line

# Build rule for target.
get_next_line: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 get_next_line
.PHONY : get_next_line

# fast build rule for target.
get_next_line/fast:
	$(MAKE) $(MAKESILENT) -f lib/get_next_line/CMakeFiles/get_next_line.dir/build.make lib/get_next_line/CMakeFiles/get_next_line.dir/build
.PHONY : get_next_line/fast

src/core/hit_record.o: src/core/hit_record.c.o
.PHONY : src/core/hit_record.o

# target to build an object file
src/core/hit_record.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/core/hit_record.c.o
.PHONY : src/core/hit_record.c.o

src/core/hit_record.i: src/core/hit_record.c.i
.PHONY : src/core/hit_record.i

# target to preprocess a source file
src/core/hit_record.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/core/hit_record.c.i
.PHONY : src/core/hit_record.c.i

src/core/hit_record.s: src/core/hit_record.c.s
.PHONY : src/core/hit_record.s

# target to generate assembly for a file
src/core/hit_record.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/core/hit_record.c.s
.PHONY : src/core/hit_record.c.s

src/geometry/aabb.o: src/geometry/aabb.c.o
.PHONY : src/geometry/aabb.o

# target to build an object file
src/geometry/aabb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/aabb.c.o
.PHONY : src/geometry/aabb.c.o

src/geometry/aabb.i: src/geometry/aabb.c.i
.PHONY : src/geometry/aabb.i

# target to preprocess a source file
src/geometry/aabb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/aabb.c.i
.PHONY : src/geometry/aabb.c.i

src/geometry/aabb.s: src/geometry/aabb.c.s
.PHONY : src/geometry/aabb.s

# target to generate assembly for a file
src/geometry/aabb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/aabb.c.s
.PHONY : src/geometry/aabb.c.s

src/geometry/bvh.o: src/geometry/bvh.c.o
.PHONY : src/geometry/bvh.o

# target to build an object file
src/geometry/bvh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/bvh.c.o
.PHONY : src/geometry/bvh.c.o

src/geometry/bvh.i: src/geometry/bvh.c.i
.PHONY : src/geometry/bvh.i

# target to preprocess a source file
src/geometry/bvh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/bvh.c.i
.PHONY : src/geometry/bvh.c.i

src/geometry/bvh.s: src/geometry/bvh.c.s
.PHONY : src/geometry/bvh.s

# target to generate assembly for a file
src/geometry/bvh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/bvh.c.s
.PHONY : src/geometry/bvh.c.s

src/geometry/objects/box.o: src/geometry/objects/box.c.o
.PHONY : src/geometry/objects/box.o

# target to build an object file
src/geometry/objects/box.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/box.c.o
.PHONY : src/geometry/objects/box.c.o

src/geometry/objects/box.i: src/geometry/objects/box.c.i
.PHONY : src/geometry/objects/box.i

# target to preprocess a source file
src/geometry/objects/box.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/box.c.i
.PHONY : src/geometry/objects/box.c.i

src/geometry/objects/box.s: src/geometry/objects/box.c.s
.PHONY : src/geometry/objects/box.s

# target to generate assembly for a file
src/geometry/objects/box.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/box.c.s
.PHONY : src/geometry/objects/box.c.s

src/geometry/objects/hittable.o: src/geometry/objects/hittable.c.o
.PHONY : src/geometry/objects/hittable.o

# target to build an object file
src/geometry/objects/hittable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/hittable.c.o
.PHONY : src/geometry/objects/hittable.c.o

src/geometry/objects/hittable.i: src/geometry/objects/hittable.c.i
.PHONY : src/geometry/objects/hittable.i

# target to preprocess a source file
src/geometry/objects/hittable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/hittable.c.i
.PHONY : src/geometry/objects/hittable.c.i

src/geometry/objects/hittable.s: src/geometry/objects/hittable.c.s
.PHONY : src/geometry/objects/hittable.s

# target to generate assembly for a file
src/geometry/objects/hittable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/hittable.c.s
.PHONY : src/geometry/objects/hittable.c.s

src/geometry/objects/hittable_list.o: src/geometry/objects/hittable_list.c.o
.PHONY : src/geometry/objects/hittable_list.o

# target to build an object file
src/geometry/objects/hittable_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/hittable_list.c.o
.PHONY : src/geometry/objects/hittable_list.c.o

src/geometry/objects/hittable_list.i: src/geometry/objects/hittable_list.c.i
.PHONY : src/geometry/objects/hittable_list.i

# target to preprocess a source file
src/geometry/objects/hittable_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/hittable_list.c.i
.PHONY : src/geometry/objects/hittable_list.c.i

src/geometry/objects/hittable_list.s: src/geometry/objects/hittable_list.c.s
.PHONY : src/geometry/objects/hittable_list.s

# target to generate assembly for a file
src/geometry/objects/hittable_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/hittable_list.c.s
.PHONY : src/geometry/objects/hittable_list.c.s

src/geometry/objects/instance.o: src/geometry/objects/instance.c.o
.PHONY : src/geometry/objects/instance.o

# target to build an object file
src/geometry/objects/instance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/instance.c.o
.PHONY : src/geometry/objects/instance.c.o

src/geometry/objects/instance.i: src/geometry/objects/instance.c.i
.PHONY : src/geometry/objects/instance.i

# target to preprocess a source file
src/geometry/objects/instance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/instance.c.i
.PHONY : src/geometry/objects/instance.c.i

src/geometry/objects/instance.s: src/geometry/objects/instance.c.s
.PHONY : src/geometry/objects/instance.s

# target to generate assembly for a file
src/geometry/objects/instance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/instance.c.s
.PHONY : src/geometry/objects/instance.c.s

src/geometry/objects/moving_sphere.o: src/geometry/objects/moving_sphere.c.o
.PHONY : src/geometry/objects/moving_sphere.o

# target to build an object file
src/geometry/objects/moving_sphere.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/moving_sphere.c.o
.PHONY : src/geometry/objects/moving_sphere.c.o

src/geometry/objects/moving_sphere.i: src/geometry/objects/moving_sphere.c.i
.PHONY : src/geometry/objects/moving_sphere.i

# target to preprocess a source file
src/geometry/objects/moving_sphere.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/moving_sphere.c.i
.PHONY : src/geometry/objects/moving_sphere.c.i

src/geometry/objects/moving_sphere.s: src/geometry/objects/moving_sphere.c.s
.PHONY : src/geometry/objects/moving_sphere.s

# target to generate assembly for a file
src/geometry/objects/moving_sphere.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/moving_sphere.c.s
.PHONY : src/geometry/objects/moving_sphere.c.s

src/geometry/objects/pdfs/pdf.o: src/geometry/objects/pdfs/pdf.c.o
.PHONY : src/geometry/objects/pdfs/pdf.o

# target to build an object file
src/geometry/objects/pdfs/pdf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/pdfs/pdf.c.o
.PHONY : src/geometry/objects/pdfs/pdf.c.o

src/geometry/objects/pdfs/pdf.i: src/geometry/objects/pdfs/pdf.c.i
.PHONY : src/geometry/objects/pdfs/pdf.i

# target to preprocess a source file
src/geometry/objects/pdfs/pdf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/pdfs/pdf.c.i
.PHONY : src/geometry/objects/pdfs/pdf.c.i

src/geometry/objects/pdfs/pdf.s: src/geometry/objects/pdfs/pdf.c.s
.PHONY : src/geometry/objects/pdfs/pdf.s

# target to generate assembly for a file
src/geometry/objects/pdfs/pdf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/pdfs/pdf.c.s
.PHONY : src/geometry/objects/pdfs/pdf.c.s

src/geometry/objects/quad.o: src/geometry/objects/quad.c.o
.PHONY : src/geometry/objects/quad.o

# target to build an object file
src/geometry/objects/quad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/quad.c.o
.PHONY : src/geometry/objects/quad.c.o

src/geometry/objects/quad.i: src/geometry/objects/quad.c.i
.PHONY : src/geometry/objects/quad.i

# target to preprocess a source file
src/geometry/objects/quad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/quad.c.i
.PHONY : src/geometry/objects/quad.c.i

src/geometry/objects/quad.s: src/geometry/objects/quad.c.s
.PHONY : src/geometry/objects/quad.s

# target to generate assembly for a file
src/geometry/objects/quad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/quad.c.s
.PHONY : src/geometry/objects/quad.c.s

src/geometry/objects/sphere.o: src/geometry/objects/sphere.c.o
.PHONY : src/geometry/objects/sphere.o

# target to build an object file
src/geometry/objects/sphere.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/sphere.c.o
.PHONY : src/geometry/objects/sphere.c.o

src/geometry/objects/sphere.i: src/geometry/objects/sphere.c.i
.PHONY : src/geometry/objects/sphere.i

# target to preprocess a source file
src/geometry/objects/sphere.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/sphere.c.i
.PHONY : src/geometry/objects/sphere.c.i

src/geometry/objects/sphere.s: src/geometry/objects/sphere.c.s
.PHONY : src/geometry/objects/sphere.s

# target to generate assembly for a file
src/geometry/objects/sphere.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/geometry/objects/sphere.c.s
.PHONY : src/geometry/objects/sphere.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/main.c.s
.PHONY : src/main.c.s

src/math/matrix3.o: src/math/matrix3.c.o
.PHONY : src/math/matrix3.o

# target to build an object file
src/math/matrix3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/math/matrix3.c.o
.PHONY : src/math/matrix3.c.o

src/math/matrix3.i: src/math/matrix3.c.i
.PHONY : src/math/matrix3.i

# target to preprocess a source file
src/math/matrix3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/math/matrix3.c.i
.PHONY : src/math/matrix3.c.i

src/math/matrix3.s: src/math/matrix3.c.s
.PHONY : src/math/matrix3.s

# target to generate assembly for a file
src/math/matrix3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/math/matrix3.c.s
.PHONY : src/math/matrix3.c.s

src/math/random.o: src/math/random.c.o
.PHONY : src/math/random.o

# target to build an object file
src/math/random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/math/random.c.o
.PHONY : src/math/random.c.o

src/math/random.i: src/math/random.c.i
.PHONY : src/math/random.i

# target to preprocess a source file
src/math/random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/math/random.c.i
.PHONY : src/math/random.c.i

src/math/random.s: src/math/random.c.s
.PHONY : src/math/random.s

# target to generate assembly for a file
src/math/random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/math/random.c.s
.PHONY : src/math/random.c.s

src/renderer/image_save.o: src/renderer/image_save.c.o
.PHONY : src/renderer/image_save.o

# target to build an object file
src/renderer/image_save.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/image_save.c.o
.PHONY : src/renderer/image_save.c.o

src/renderer/image_save.i: src/renderer/image_save.c.i
.PHONY : src/renderer/image_save.i

# target to preprocess a source file
src/renderer/image_save.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/image_save.c.i
.PHONY : src/renderer/image_save.c.i

src/renderer/image_save.s: src/renderer/image_save.c.s
.PHONY : src/renderer/image_save.s

# target to generate assembly for a file
src/renderer/image_save.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/image_save.c.s
.PHONY : src/renderer/image_save.c.s

src/renderer/mlx_setup.o: src/renderer/mlx_setup.c.o
.PHONY : src/renderer/mlx_setup.o

# target to build an object file
src/renderer/mlx_setup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/mlx_setup.c.o
.PHONY : src/renderer/mlx_setup.c.o

src/renderer/mlx_setup.i: src/renderer/mlx_setup.c.i
.PHONY : src/renderer/mlx_setup.i

# target to preprocess a source file
src/renderer/mlx_setup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/mlx_setup.c.i
.PHONY : src/renderer/mlx_setup.c.i

src/renderer/mlx_setup.s: src/renderer/mlx_setup.c.s
.PHONY : src/renderer/mlx_setup.s

# target to generate assembly for a file
src/renderer/mlx_setup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/mlx_setup.c.s
.PHONY : src/renderer/mlx_setup.c.s

src/renderer/render_context.o: src/renderer/render_context.c.o
.PHONY : src/renderer/render_context.o

# target to build an object file
src/renderer/render_context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/render_context.c.o
.PHONY : src/renderer/render_context.c.o

src/renderer/render_context.i: src/renderer/render_context.c.i
.PHONY : src/renderer/render_context.i

# target to preprocess a source file
src/renderer/render_context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/render_context.c.i
.PHONY : src/renderer/render_context.c.i

src/renderer/render_context.s: src/renderer/render_context.c.s
.PHONY : src/renderer/render_context.s

# target to generate assembly for a file
src/renderer/render_context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/render_context.c.s
.PHONY : src/renderer/render_context.c.s

src/renderer/render_launch.o: src/renderer/render_launch.c.o
.PHONY : src/renderer/render_launch.o

# target to build an object file
src/renderer/render_launch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/render_launch.c.o
.PHONY : src/renderer/render_launch.c.o

src/renderer/render_launch.i: src/renderer/render_launch.c.i
.PHONY : src/renderer/render_launch.i

# target to preprocess a source file
src/renderer/render_launch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/render_launch.c.i
.PHONY : src/renderer/render_launch.c.i

src/renderer/render_launch.s: src/renderer/render_launch.c.s
.PHONY : src/renderer/render_launch.s

# target to generate assembly for a file
src/renderer/render_launch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/render_launch.c.s
.PHONY : src/renderer/render_launch.c.s

src/renderer/threads/sync_unix.o: src/renderer/threads/sync_unix.c.o
.PHONY : src/renderer/threads/sync_unix.o

# target to build an object file
src/renderer/threads/sync_unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/sync_unix.c.o
.PHONY : src/renderer/threads/sync_unix.c.o

src/renderer/threads/sync_unix.i: src/renderer/threads/sync_unix.c.i
.PHONY : src/renderer/threads/sync_unix.i

# target to preprocess a source file
src/renderer/threads/sync_unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/sync_unix.c.i
.PHONY : src/renderer/threads/sync_unix.c.i

src/renderer/threads/sync_unix.s: src/renderer/threads/sync_unix.c.s
.PHONY : src/renderer/threads/sync_unix.s

# target to generate assembly for a file
src/renderer/threads/sync_unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/sync_unix.c.s
.PHONY : src/renderer/threads/sync_unix.c.s

src/renderer/threads/thread_pool.o: src/renderer/threads/thread_pool.c.o
.PHONY : src/renderer/threads/thread_pool.o

# target to build an object file
src/renderer/threads/thread_pool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/thread_pool.c.o
.PHONY : src/renderer/threads/thread_pool.c.o

src/renderer/threads/thread_pool.i: src/renderer/threads/thread_pool.c.i
.PHONY : src/renderer/threads/thread_pool.i

# target to preprocess a source file
src/renderer/threads/thread_pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/thread_pool.c.i
.PHONY : src/renderer/threads/thread_pool.c.i

src/renderer/threads/thread_pool.s: src/renderer/threads/thread_pool.c.s
.PHONY : src/renderer/threads/thread_pool.s

# target to generate assembly for a file
src/renderer/threads/thread_pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/thread_pool.c.s
.PHONY : src/renderer/threads/thread_pool.c.s

src/renderer/threads/thread_unix.o: src/renderer/threads/thread_unix.c.o
.PHONY : src/renderer/threads/thread_unix.o

# target to build an object file
src/renderer/threads/thread_unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/thread_unix.c.o
.PHONY : src/renderer/threads/thread_unix.c.o

src/renderer/threads/thread_unix.i: src/renderer/threads/thread_unix.c.i
.PHONY : src/renderer/threads/thread_unix.i

# target to preprocess a source file
src/renderer/threads/thread_unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/thread_unix.c.i
.PHONY : src/renderer/threads/thread_unix.c.i

src/renderer/threads/thread_unix.s: src/renderer/threads/thread_unix.c.s
.PHONY : src/renderer/threads/thread_unix.s

# target to generate assembly for a file
src/renderer/threads/thread_unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/renderer/threads/thread_unix.c.s
.PHONY : src/renderer/threads/thread_unix.c.s

src/shading/materials/diffuse_light.o: src/shading/materials/diffuse_light.c.o
.PHONY : src/shading/materials/diffuse_light.o

# target to build an object file
src/shading/materials/diffuse_light.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/diffuse_light.c.o
.PHONY : src/shading/materials/diffuse_light.c.o

src/shading/materials/diffuse_light.i: src/shading/materials/diffuse_light.c.i
.PHONY : src/shading/materials/diffuse_light.i

# target to preprocess a source file
src/shading/materials/diffuse_light.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/diffuse_light.c.i
.PHONY : src/shading/materials/diffuse_light.c.i

src/shading/materials/diffuse_light.s: src/shading/materials/diffuse_light.c.s
.PHONY : src/shading/materials/diffuse_light.s

# target to generate assembly for a file
src/shading/materials/diffuse_light.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/diffuse_light.c.s
.PHONY : src/shading/materials/diffuse_light.c.s

src/shading/materials/material.o: src/shading/materials/material.c.o
.PHONY : src/shading/materials/material.o

# target to build an object file
src/shading/materials/material.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material.c.o
.PHONY : src/shading/materials/material.c.o

src/shading/materials/material.i: src/shading/materials/material.c.i
.PHONY : src/shading/materials/material.i

# target to preprocess a source file
src/shading/materials/material.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material.c.i
.PHONY : src/shading/materials/material.c.i

src/shading/materials/material.s: src/shading/materials/material.c.s
.PHONY : src/shading/materials/material.s

# target to generate assembly for a file
src/shading/materials/material.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material.c.s
.PHONY : src/shading/materials/material.c.s

src/shading/materials/material_dielectric.o: src/shading/materials/material_dielectric.c.o
.PHONY : src/shading/materials/material_dielectric.o

# target to build an object file
src/shading/materials/material_dielectric.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_dielectric.c.o
.PHONY : src/shading/materials/material_dielectric.c.o

src/shading/materials/material_dielectric.i: src/shading/materials/material_dielectric.c.i
.PHONY : src/shading/materials/material_dielectric.i

# target to preprocess a source file
src/shading/materials/material_dielectric.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_dielectric.c.i
.PHONY : src/shading/materials/material_dielectric.c.i

src/shading/materials/material_dielectric.s: src/shading/materials/material_dielectric.c.s
.PHONY : src/shading/materials/material_dielectric.s

# target to generate assembly for a file
src/shading/materials/material_dielectric.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_dielectric.c.s
.PHONY : src/shading/materials/material_dielectric.c.s

src/shading/materials/material_isotropic.o: src/shading/materials/material_isotropic.c.o
.PHONY : src/shading/materials/material_isotropic.o

# target to build an object file
src/shading/materials/material_isotropic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_isotropic.c.o
.PHONY : src/shading/materials/material_isotropic.c.o

src/shading/materials/material_isotropic.i: src/shading/materials/material_isotropic.c.i
.PHONY : src/shading/materials/material_isotropic.i

# target to preprocess a source file
src/shading/materials/material_isotropic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_isotropic.c.i
.PHONY : src/shading/materials/material_isotropic.c.i

src/shading/materials/material_isotropic.s: src/shading/materials/material_isotropic.c.s
.PHONY : src/shading/materials/material_isotropic.s

# target to generate assembly for a file
src/shading/materials/material_isotropic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_isotropic.c.s
.PHONY : src/shading/materials/material_isotropic.c.s

src/shading/materials/material_lambertian.o: src/shading/materials/material_lambertian.c.o
.PHONY : src/shading/materials/material_lambertian.o

# target to build an object file
src/shading/materials/material_lambertian.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_lambertian.c.o
.PHONY : src/shading/materials/material_lambertian.c.o

src/shading/materials/material_lambertian.i: src/shading/materials/material_lambertian.c.i
.PHONY : src/shading/materials/material_lambertian.i

# target to preprocess a source file
src/shading/materials/material_lambertian.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_lambertian.c.i
.PHONY : src/shading/materials/material_lambertian.c.i

src/shading/materials/material_lambertian.s: src/shading/materials/material_lambertian.c.s
.PHONY : src/shading/materials/material_lambertian.s

# target to generate assembly for a file
src/shading/materials/material_lambertian.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_lambertian.c.s
.PHONY : src/shading/materials/material_lambertian.c.s

src/shading/materials/material_metal.o: src/shading/materials/material_metal.c.o
.PHONY : src/shading/materials/material_metal.o

# target to build an object file
src/shading/materials/material_metal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_metal.c.o
.PHONY : src/shading/materials/material_metal.c.o

src/shading/materials/material_metal.i: src/shading/materials/material_metal.c.i
.PHONY : src/shading/materials/material_metal.i

# target to preprocess a source file
src/shading/materials/material_metal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_metal.c.i
.PHONY : src/shading/materials/material_metal.c.i

src/shading/materials/material_metal.s: src/shading/materials/material_metal.c.s
.PHONY : src/shading/materials/material_metal.s

# target to generate assembly for a file
src/shading/materials/material_metal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/materials/material_metal.c.s
.PHONY : src/shading/materials/material_metal.c.s

src/shading/textures/checker_pattern.o: src/shading/textures/checker_pattern.c.o
.PHONY : src/shading/textures/checker_pattern.o

# target to build an object file
src/shading/textures/checker_pattern.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/checker_pattern.c.o
.PHONY : src/shading/textures/checker_pattern.c.o

src/shading/textures/checker_pattern.i: src/shading/textures/checker_pattern.c.i
.PHONY : src/shading/textures/checker_pattern.i

# target to preprocess a source file
src/shading/textures/checker_pattern.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/checker_pattern.c.i
.PHONY : src/shading/textures/checker_pattern.c.i

src/shading/textures/checker_pattern.s: src/shading/textures/checker_pattern.c.s
.PHONY : src/shading/textures/checker_pattern.s

# target to generate assembly for a file
src/shading/textures/checker_pattern.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/checker_pattern.c.s
.PHONY : src/shading/textures/checker_pattern.c.s

src/shading/textures/color.o: src/shading/textures/color.c.o
.PHONY : src/shading/textures/color.o

# target to build an object file
src/shading/textures/color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/color.c.o
.PHONY : src/shading/textures/color.c.o

src/shading/textures/color.i: src/shading/textures/color.c.i
.PHONY : src/shading/textures/color.i

# target to preprocess a source file
src/shading/textures/color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/color.c.i
.PHONY : src/shading/textures/color.c.i

src/shading/textures/color.s: src/shading/textures/color.c.s
.PHONY : src/shading/textures/color.s

# target to generate assembly for a file
src/shading/textures/color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/color.c.s
.PHONY : src/shading/textures/color.c.s

src/shading/textures/constant_medium.o: src/shading/textures/constant_medium.c.o
.PHONY : src/shading/textures/constant_medium.o

# target to build an object file
src/shading/textures/constant_medium.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/constant_medium.c.o
.PHONY : src/shading/textures/constant_medium.c.o

src/shading/textures/constant_medium.i: src/shading/textures/constant_medium.c.i
.PHONY : src/shading/textures/constant_medium.i

# target to preprocess a source file
src/shading/textures/constant_medium.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/constant_medium.c.i
.PHONY : src/shading/textures/constant_medium.c.i

src/shading/textures/constant_medium.s: src/shading/textures/constant_medium.c.s
.PHONY : src/shading/textures/constant_medium.s

# target to generate assembly for a file
src/shading/textures/constant_medium.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/constant_medium.c.s
.PHONY : src/shading/textures/constant_medium.c.s

src/shading/textures/image_texture.o: src/shading/textures/image_texture.c.o
.PHONY : src/shading/textures/image_texture.o

# target to build an object file
src/shading/textures/image_texture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/image_texture.c.o
.PHONY : src/shading/textures/image_texture.c.o

src/shading/textures/image_texture.i: src/shading/textures/image_texture.c.i
.PHONY : src/shading/textures/image_texture.i

# target to preprocess a source file
src/shading/textures/image_texture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/image_texture.c.i
.PHONY : src/shading/textures/image_texture.c.i

src/shading/textures/image_texture.s: src/shading/textures/image_texture.c.s
.PHONY : src/shading/textures/image_texture.s

# target to generate assembly for a file
src/shading/textures/image_texture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/image_texture.c.s
.PHONY : src/shading/textures/image_texture.c.s

src/shading/textures/perlin.o: src/shading/textures/perlin.c.o
.PHONY : src/shading/textures/perlin.o

# target to build an object file
src/shading/textures/perlin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/perlin.c.o
.PHONY : src/shading/textures/perlin.c.o

src/shading/textures/perlin.i: src/shading/textures/perlin.c.i
.PHONY : src/shading/textures/perlin.i

# target to preprocess a source file
src/shading/textures/perlin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/perlin.c.i
.PHONY : src/shading/textures/perlin.c.i

src/shading/textures/perlin.s: src/shading/textures/perlin.c.s
.PHONY : src/shading/textures/perlin.s

# target to generate assembly for a file
src/shading/textures/perlin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/perlin.c.s
.PHONY : src/shading/textures/perlin.c.s

src/shading/textures/solid_colour.o: src/shading/textures/solid_colour.c.o
.PHONY : src/shading/textures/solid_colour.o

# target to build an object file
src/shading/textures/solid_colour.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/solid_colour.c.o
.PHONY : src/shading/textures/solid_colour.c.o

src/shading/textures/solid_colour.i: src/shading/textures/solid_colour.c.i
.PHONY : src/shading/textures/solid_colour.i

# target to preprocess a source file
src/shading/textures/solid_colour.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/solid_colour.c.i
.PHONY : src/shading/textures/solid_colour.c.i

src/shading/textures/solid_colour.s: src/shading/textures/solid_colour.c.s
.PHONY : src/shading/textures/solid_colour.s

# target to generate assembly for a file
src/shading/textures/solid_colour.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/solid_colour.c.s
.PHONY : src/shading/textures/solid_colour.c.s

src/shading/textures/texture.o: src/shading/textures/texture.c.o
.PHONY : src/shading/textures/texture.o

# target to build an object file
src/shading/textures/texture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/texture.c.o
.PHONY : src/shading/textures/texture.c.o

src/shading/textures/texture.i: src/shading/textures/texture.c.i
.PHONY : src/shading/textures/texture.i

# target to preprocess a source file
src/shading/textures/texture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/texture.c.i
.PHONY : src/shading/textures/texture.c.i

src/shading/textures/texture.s: src/shading/textures/texture.c.s
.PHONY : src/shading/textures/texture.s

# target to generate assembly for a file
src/shading/textures/texture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/shading/textures/texture.c.s
.PHONY : src/shading/textures/texture.c.s

src/system/scene_setup.o: src/system/scene_setup.c.o
.PHONY : src/system/scene_setup.o

# target to build an object file
src/system/scene_setup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/system/scene_setup.c.o
.PHONY : src/system/scene_setup.c.o

src/system/scene_setup.i: src/system/scene_setup.c.i
.PHONY : src/system/scene_setup.i

# target to preprocess a source file
src/system/scene_setup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/system/scene_setup.c.i
.PHONY : src/system/scene_setup.c.i

src/system/scene_setup.s: src/system/scene_setup.c.s
.PHONY : src/system/scene_setup.s

# target to generate assembly for a file
src/system/scene_setup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/system/scene_setup.c.s
.PHONY : src/system/scene_setup.c.s

src/system/scenes.o: src/system/scenes.c.o
.PHONY : src/system/scenes.o

# target to build an object file
src/system/scenes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/system/scenes.c.o
.PHONY : src/system/scenes.c.o

src/system/scenes.i: src/system/scenes.c.i
.PHONY : src/system/scenes.i

# target to preprocess a source file
src/system/scenes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/system/scenes.c.i
.PHONY : src/system/scenes.c.i

src/system/scenes.s: src/system/scenes.c.s
.PHONY : src/system/scenes.s

# target to generate assembly for a file
src/system/scenes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/system/scenes.c.s
.PHONY : src/system/scenes.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ft"
	@echo "... get_next_line"
	@echo "... miniRT"
	@echo "... mlx42"
	@echo "... src/core/hit_record.o"
	@echo "... src/core/hit_record.i"
	@echo "... src/core/hit_record.s"
	@echo "... src/geometry/aabb.o"
	@echo "... src/geometry/aabb.i"
	@echo "... src/geometry/aabb.s"
	@echo "... src/geometry/bvh.o"
	@echo "... src/geometry/bvh.i"
	@echo "... src/geometry/bvh.s"
	@echo "... src/geometry/objects/box.o"
	@echo "... src/geometry/objects/box.i"
	@echo "... src/geometry/objects/box.s"
	@echo "... src/geometry/objects/hittable.o"
	@echo "... src/geometry/objects/hittable.i"
	@echo "... src/geometry/objects/hittable.s"
	@echo "... src/geometry/objects/hittable_list.o"
	@echo "... src/geometry/objects/hittable_list.i"
	@echo "... src/geometry/objects/hittable_list.s"
	@echo "... src/geometry/objects/instance.o"
	@echo "... src/geometry/objects/instance.i"
	@echo "... src/geometry/objects/instance.s"
	@echo "... src/geometry/objects/moving_sphere.o"
	@echo "... src/geometry/objects/moving_sphere.i"
	@echo "... src/geometry/objects/moving_sphere.s"
	@echo "... src/geometry/objects/pdfs/pdf.o"
	@echo "... src/geometry/objects/pdfs/pdf.i"
	@echo "... src/geometry/objects/pdfs/pdf.s"
	@echo "... src/geometry/objects/quad.o"
	@echo "... src/geometry/objects/quad.i"
	@echo "... src/geometry/objects/quad.s"
	@echo "... src/geometry/objects/sphere.o"
	@echo "... src/geometry/objects/sphere.i"
	@echo "... src/geometry/objects/sphere.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math/matrix3.o"
	@echo "... src/math/matrix3.i"
	@echo "... src/math/matrix3.s"
	@echo "... src/math/random.o"
	@echo "... src/math/random.i"
	@echo "... src/math/random.s"
	@echo "... src/renderer/image_save.o"
	@echo "... src/renderer/image_save.i"
	@echo "... src/renderer/image_save.s"
	@echo "... src/renderer/mlx_setup.o"
	@echo "... src/renderer/mlx_setup.i"
	@echo "... src/renderer/mlx_setup.s"
	@echo "... src/renderer/render_context.o"
	@echo "... src/renderer/render_context.i"
	@echo "... src/renderer/render_context.s"
	@echo "... src/renderer/render_launch.o"
	@echo "... src/renderer/render_launch.i"
	@echo "... src/renderer/render_launch.s"
	@echo "... src/renderer/threads/sync_unix.o"
	@echo "... src/renderer/threads/sync_unix.i"
	@echo "... src/renderer/threads/sync_unix.s"
	@echo "... src/renderer/threads/thread_pool.o"
	@echo "... src/renderer/threads/thread_pool.i"
	@echo "... src/renderer/threads/thread_pool.s"
	@echo "... src/renderer/threads/thread_unix.o"
	@echo "... src/renderer/threads/thread_unix.i"
	@echo "... src/renderer/threads/thread_unix.s"
	@echo "... src/shading/materials/diffuse_light.o"
	@echo "... src/shading/materials/diffuse_light.i"
	@echo "... src/shading/materials/diffuse_light.s"
	@echo "... src/shading/materials/material.o"
	@echo "... src/shading/materials/material.i"
	@echo "... src/shading/materials/material.s"
	@echo "... src/shading/materials/material_dielectric.o"
	@echo "... src/shading/materials/material_dielectric.i"
	@echo "... src/shading/materials/material_dielectric.s"
	@echo "... src/shading/materials/material_isotropic.o"
	@echo "... src/shading/materials/material_isotropic.i"
	@echo "... src/shading/materials/material_isotropic.s"
	@echo "... src/shading/materials/material_lambertian.o"
	@echo "... src/shading/materials/material_lambertian.i"
	@echo "... src/shading/materials/material_lambertian.s"
	@echo "... src/shading/materials/material_metal.o"
	@echo "... src/shading/materials/material_metal.i"
	@echo "... src/shading/materials/material_metal.s"
	@echo "... src/shading/textures/checker_pattern.o"
	@echo "... src/shading/textures/checker_pattern.i"
	@echo "... src/shading/textures/checker_pattern.s"
	@echo "... src/shading/textures/color.o"
	@echo "... src/shading/textures/color.i"
	@echo "... src/shading/textures/color.s"
	@echo "... src/shading/textures/constant_medium.o"
	@echo "... src/shading/textures/constant_medium.i"
	@echo "... src/shading/textures/constant_medium.s"
	@echo "... src/shading/textures/image_texture.o"
	@echo "... src/shading/textures/image_texture.i"
	@echo "... src/shading/textures/image_texture.s"
	@echo "... src/shading/textures/perlin.o"
	@echo "... src/shading/textures/perlin.i"
	@echo "... src/shading/textures/perlin.s"
	@echo "... src/shading/textures/solid_colour.o"
	@echo "... src/shading/textures/solid_colour.i"
	@echo "... src/shading/textures/solid_colour.s"
	@echo "... src/shading/textures/texture.o"
	@echo "... src/shading/textures/texture.i"
	@echo "... src/shading/textures/texture.s"
	@echo "... src/system/scene_setup.o"
	@echo "... src/system/scene_setup.i"
	@echo "... src/system/scene_setup.s"
	@echo "... src/system/scenes.o"
	@echo "... src/system/scenes.i"
	@echo "... src/system/scenes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

