# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/miniRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/miniRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/miniRT/CMakeFiles /workspaces/miniRT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/miniRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named miniRT

# Build rule for target.
miniRT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 miniRT
.PHONY : miniRT

# fast build rule for target.
miniRT/fast:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/build
.PHONY : miniRT/fast

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) -f lib/Libft/CMakeFiles/ft.dir/build.make lib/Libft/CMakeFiles/ft.dir/build
.PHONY : ft/fast

#=============================================================================
# Target rules for targets named mlx42

# Build rule for target.
mlx42: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlx42
.PHONY : mlx42

# fast build rule for target.
mlx42/fast:
	$(MAKE) -f lib/MLX42/CMakeFiles/mlx42.dir/build.make lib/MLX42/CMakeFiles/mlx42.dir/build
.PHONY : mlx42/fast

#=============================================================================
# Target rules for targets named get_next_line

# Build rule for target.
get_next_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_next_line
.PHONY : get_next_line

# fast build rule for target.
get_next_line/fast:
	$(MAKE) -f lib/get_next_line/CMakeFiles/get_next_line.dir/build.make lib/get_next_line/CMakeFiles/get_next_line.dir/build
.PHONY : get_next_line/fast

src/image_save.o: src/image_save.c.o

.PHONY : src/image_save.o

# target to build an object file
src/image_save.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/image_save.c.o
.PHONY : src/image_save.c.o

src/image_save.i: src/image_save.c.i

.PHONY : src/image_save.i

# target to preprocess a source file
src/image_save.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/image_save.c.i
.PHONY : src/image_save.c.i

src/image_save.s: src/image_save.c.s

.PHONY : src/image_save.s

# target to generate assembly for a file
src/image_save.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/image_save.c.s
.PHONY : src/image_save.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/main.c.s
.PHONY : src/main.c.s

src/random.o: src/random.c.o

.PHONY : src/random.o

# target to build an object file
src/random.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/random.c.o
.PHONY : src/random.c.o

src/random.i: src/random.c.i

.PHONY : src/random.i

# target to preprocess a source file
src/random.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/random.c.i
.PHONY : src/random.c.i

src/random.s: src/random.c.s

.PHONY : src/random.s

# target to generate assembly for a file
src/random.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/random.c.s
.PHONY : src/random.c.s

src/render/aabb.o: src/render/aabb.c.o

.PHONY : src/render/aabb.o

# target to build an object file
src/render/aabb.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/aabb.c.o
.PHONY : src/render/aabb.c.o

src/render/aabb.i: src/render/aabb.c.i

.PHONY : src/render/aabb.i

# target to preprocess a source file
src/render/aabb.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/aabb.c.i
.PHONY : src/render/aabb.c.i

src/render/aabb.s: src/render/aabb.c.s

.PHONY : src/render/aabb.s

# target to generate assembly for a file
src/render/aabb.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/aabb.c.s
.PHONY : src/render/aabb.c.s

src/render/box.o: src/render/box.c.o

.PHONY : src/render/box.o

# target to build an object file
src/render/box.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/box.c.o
.PHONY : src/render/box.c.o

src/render/box.i: src/render/box.c.i

.PHONY : src/render/box.i

# target to preprocess a source file
src/render/box.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/box.c.i
.PHONY : src/render/box.c.i

src/render/box.s: src/render/box.c.s

.PHONY : src/render/box.s

# target to generate assembly for a file
src/render/box.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/box.c.s
.PHONY : src/render/box.c.s

src/render/bvh.o: src/render/bvh.c.o

.PHONY : src/render/bvh.o

# target to build an object file
src/render/bvh.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/bvh.c.o
.PHONY : src/render/bvh.c.o

src/render/bvh.i: src/render/bvh.c.i

.PHONY : src/render/bvh.i

# target to preprocess a source file
src/render/bvh.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/bvh.c.i
.PHONY : src/render/bvh.c.i

src/render/bvh.s: src/render/bvh.c.s

.PHONY : src/render/bvh.s

# target to generate assembly for a file
src/render/bvh.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/bvh.c.s
.PHONY : src/render/bvh.c.s

src/render/color.o: src/render/color.c.o

.PHONY : src/render/color.o

# target to build an object file
src/render/color.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/color.c.o
.PHONY : src/render/color.c.o

src/render/color.i: src/render/color.c.i

.PHONY : src/render/color.i

# target to preprocess a source file
src/render/color.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/color.c.i
.PHONY : src/render/color.c.i

src/render/color.s: src/render/color.c.s

.PHONY : src/render/color.s

# target to generate assembly for a file
src/render/color.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/color.c.s
.PHONY : src/render/color.c.s

src/render/constant_medium.o: src/render/constant_medium.c.o

.PHONY : src/render/constant_medium.o

# target to build an object file
src/render/constant_medium.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/constant_medium.c.o
.PHONY : src/render/constant_medium.c.o

src/render/constant_medium.i: src/render/constant_medium.c.i

.PHONY : src/render/constant_medium.i

# target to preprocess a source file
src/render/constant_medium.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/constant_medium.c.i
.PHONY : src/render/constant_medium.c.i

src/render/constant_medium.s: src/render/constant_medium.c.s

.PHONY : src/render/constant_medium.s

# target to generate assembly for a file
src/render/constant_medium.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/constant_medium.c.s
.PHONY : src/render/constant_medium.c.s

src/render/hit_record.o: src/render/hit_record.c.o

.PHONY : src/render/hit_record.o

# target to build an object file
src/render/hit_record.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hit_record.c.o
.PHONY : src/render/hit_record.c.o

src/render/hit_record.i: src/render/hit_record.c.i

.PHONY : src/render/hit_record.i

# target to preprocess a source file
src/render/hit_record.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hit_record.c.i
.PHONY : src/render/hit_record.c.i

src/render/hit_record.s: src/render/hit_record.c.s

.PHONY : src/render/hit_record.s

# target to generate assembly for a file
src/render/hit_record.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hit_record.c.s
.PHONY : src/render/hit_record.c.s

src/render/hittable.o: src/render/hittable.c.o

.PHONY : src/render/hittable.o

# target to build an object file
src/render/hittable.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hittable.c.o
.PHONY : src/render/hittable.c.o

src/render/hittable.i: src/render/hittable.c.i

.PHONY : src/render/hittable.i

# target to preprocess a source file
src/render/hittable.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hittable.c.i
.PHONY : src/render/hittable.c.i

src/render/hittable.s: src/render/hittable.c.s

.PHONY : src/render/hittable.s

# target to generate assembly for a file
src/render/hittable.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hittable.c.s
.PHONY : src/render/hittable.c.s

src/render/hittable_list.o: src/render/hittable_list.c.o

.PHONY : src/render/hittable_list.o

# target to build an object file
src/render/hittable_list.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hittable_list.c.o
.PHONY : src/render/hittable_list.c.o

src/render/hittable_list.i: src/render/hittable_list.c.i

.PHONY : src/render/hittable_list.i

# target to preprocess a source file
src/render/hittable_list.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hittable_list.c.i
.PHONY : src/render/hittable_list.c.i

src/render/hittable_list.s: src/render/hittable_list.c.s

.PHONY : src/render/hittable_list.s

# target to generate assembly for a file
src/render/hittable_list.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/hittable_list.c.s
.PHONY : src/render/hittable_list.c.s

src/render/instance.o: src/render/instance.c.o

.PHONY : src/render/instance.o

# target to build an object file
src/render/instance.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/instance.c.o
.PHONY : src/render/instance.c.o

src/render/instance.i: src/render/instance.c.i

.PHONY : src/render/instance.i

# target to preprocess a source file
src/render/instance.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/instance.c.i
.PHONY : src/render/instance.c.i

src/render/instance.s: src/render/instance.c.s

.PHONY : src/render/instance.s

# target to generate assembly for a file
src/render/instance.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/instance.c.s
.PHONY : src/render/instance.c.s

src/render/material.o: src/render/material.c.o

.PHONY : src/render/material.o

# target to build an object file
src/render/material.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material.c.o
.PHONY : src/render/material.c.o

src/render/material.i: src/render/material.c.i

.PHONY : src/render/material.i

# target to preprocess a source file
src/render/material.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material.c.i
.PHONY : src/render/material.c.i

src/render/material.s: src/render/material.c.s

.PHONY : src/render/material.s

# target to generate assembly for a file
src/render/material.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material.c.s
.PHONY : src/render/material.c.s

src/render/material_dielectric.o: src/render/material_dielectric.c.o

.PHONY : src/render/material_dielectric.o

# target to build an object file
src/render/material_dielectric.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_dielectric.c.o
.PHONY : src/render/material_dielectric.c.o

src/render/material_dielectric.i: src/render/material_dielectric.c.i

.PHONY : src/render/material_dielectric.i

# target to preprocess a source file
src/render/material_dielectric.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_dielectric.c.i
.PHONY : src/render/material_dielectric.c.i

src/render/material_dielectric.s: src/render/material_dielectric.c.s

.PHONY : src/render/material_dielectric.s

# target to generate assembly for a file
src/render/material_dielectric.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_dielectric.c.s
.PHONY : src/render/material_dielectric.c.s

src/render/material_diffuse_light.o: src/render/material_diffuse_light.c.o

.PHONY : src/render/material_diffuse_light.o

# target to build an object file
src/render/material_diffuse_light.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_diffuse_light.c.o
.PHONY : src/render/material_diffuse_light.c.o

src/render/material_diffuse_light.i: src/render/material_diffuse_light.c.i

.PHONY : src/render/material_diffuse_light.i

# target to preprocess a source file
src/render/material_diffuse_light.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_diffuse_light.c.i
.PHONY : src/render/material_diffuse_light.c.i

src/render/material_diffuse_light.s: src/render/material_diffuse_light.c.s

.PHONY : src/render/material_diffuse_light.s

# target to generate assembly for a file
src/render/material_diffuse_light.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_diffuse_light.c.s
.PHONY : src/render/material_diffuse_light.c.s

src/render/material_isotropic.o: src/render/material_isotropic.c.o

.PHONY : src/render/material_isotropic.o

# target to build an object file
src/render/material_isotropic.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_isotropic.c.o
.PHONY : src/render/material_isotropic.c.o

src/render/material_isotropic.i: src/render/material_isotropic.c.i

.PHONY : src/render/material_isotropic.i

# target to preprocess a source file
src/render/material_isotropic.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_isotropic.c.i
.PHONY : src/render/material_isotropic.c.i

src/render/material_isotropic.s: src/render/material_isotropic.c.s

.PHONY : src/render/material_isotropic.s

# target to generate assembly for a file
src/render/material_isotropic.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_isotropic.c.s
.PHONY : src/render/material_isotropic.c.s

src/render/material_lambertian.o: src/render/material_lambertian.c.o

.PHONY : src/render/material_lambertian.o

# target to build an object file
src/render/material_lambertian.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_lambertian.c.o
.PHONY : src/render/material_lambertian.c.o

src/render/material_lambertian.i: src/render/material_lambertian.c.i

.PHONY : src/render/material_lambertian.i

# target to preprocess a source file
src/render/material_lambertian.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_lambertian.c.i
.PHONY : src/render/material_lambertian.c.i

src/render/material_lambertian.s: src/render/material_lambertian.c.s

.PHONY : src/render/material_lambertian.s

# target to generate assembly for a file
src/render/material_lambertian.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_lambertian.c.s
.PHONY : src/render/material_lambertian.c.s

src/render/material_metal.o: src/render/material_metal.c.o

.PHONY : src/render/material_metal.o

# target to build an object file
src/render/material_metal.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_metal.c.o
.PHONY : src/render/material_metal.c.o

src/render/material_metal.i: src/render/material_metal.c.i

.PHONY : src/render/material_metal.i

# target to preprocess a source file
src/render/material_metal.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_metal.c.i
.PHONY : src/render/material_metal.c.i

src/render/material_metal.s: src/render/material_metal.c.s

.PHONY : src/render/material_metal.s

# target to generate assembly for a file
src/render/material_metal.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/material_metal.c.s
.PHONY : src/render/material_metal.c.s

src/render/matrix3.o: src/render/matrix3.c.o

.PHONY : src/render/matrix3.o

# target to build an object file
src/render/matrix3.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/matrix3.c.o
.PHONY : src/render/matrix3.c.o

src/render/matrix3.i: src/render/matrix3.c.i

.PHONY : src/render/matrix3.i

# target to preprocess a source file
src/render/matrix3.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/matrix3.c.i
.PHONY : src/render/matrix3.c.i

src/render/matrix3.s: src/render/matrix3.c.s

.PHONY : src/render/matrix3.s

# target to generate assembly for a file
src/render/matrix3.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/matrix3.c.s
.PHONY : src/render/matrix3.c.s

src/render/moving_sphere.o: src/render/moving_sphere.c.o

.PHONY : src/render/moving_sphere.o

# target to build an object file
src/render/moving_sphere.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/moving_sphere.c.o
.PHONY : src/render/moving_sphere.c.o

src/render/moving_sphere.i: src/render/moving_sphere.c.i

.PHONY : src/render/moving_sphere.i

# target to preprocess a source file
src/render/moving_sphere.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/moving_sphere.c.i
.PHONY : src/render/moving_sphere.c.i

src/render/moving_sphere.s: src/render/moving_sphere.c.s

.PHONY : src/render/moving_sphere.s

# target to generate assembly for a file
src/render/moving_sphere.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/moving_sphere.c.s
.PHONY : src/render/moving_sphere.c.s

src/render/quad.o: src/render/quad.c.o

.PHONY : src/render/quad.o

# target to build an object file
src/render/quad.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/quad.c.o
.PHONY : src/render/quad.c.o

src/render/quad.i: src/render/quad.c.i

.PHONY : src/render/quad.i

# target to preprocess a source file
src/render/quad.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/quad.c.i
.PHONY : src/render/quad.c.i

src/render/quad.s: src/render/quad.c.s

.PHONY : src/render/quad.s

# target to generate assembly for a file
src/render/quad.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/quad.c.s
.PHONY : src/render/quad.c.s

src/render/sphere.o: src/render/sphere.c.o

.PHONY : src/render/sphere.o

# target to build an object file
src/render/sphere.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/sphere.c.o
.PHONY : src/render/sphere.c.o

src/render/sphere.i: src/render/sphere.c.i

.PHONY : src/render/sphere.i

# target to preprocess a source file
src/render/sphere.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/sphere.c.i
.PHONY : src/render/sphere.c.i

src/render/sphere.s: src/render/sphere.c.s

.PHONY : src/render/sphere.s

# target to generate assembly for a file
src/render/sphere.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render/sphere.c.s
.PHONY : src/render/sphere.c.s

src/render_context.o: src/render_context.c.o

.PHONY : src/render_context.o

# target to build an object file
src/render_context.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render_context.c.o
.PHONY : src/render_context.c.o

src/render_context.i: src/render_context.c.i

.PHONY : src/render_context.i

# target to preprocess a source file
src/render_context.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render_context.c.i
.PHONY : src/render_context.c.i

src/render_context.s: src/render_context.c.s

.PHONY : src/render_context.s

# target to generate assembly for a file
src/render_context.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/render_context.c.s
.PHONY : src/render_context.c.s

src/scenes.o: src/scenes.c.o

.PHONY : src/scenes.o

# target to build an object file
src/scenes.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/scenes.c.o
.PHONY : src/scenes.c.o

src/scenes.i: src/scenes.c.i

.PHONY : src/scenes.i

# target to preprocess a source file
src/scenes.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/scenes.c.i
.PHONY : src/scenes.c.i

src/scenes.s: src/scenes.c.s

.PHONY : src/scenes.s

# target to generate assembly for a file
src/scenes.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/scenes.c.s
.PHONY : src/scenes.c.s

src/textures/checker_pattern.o: src/textures/checker_pattern.c.o

.PHONY : src/textures/checker_pattern.o

# target to build an object file
src/textures/checker_pattern.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/checker_pattern.c.o
.PHONY : src/textures/checker_pattern.c.o

src/textures/checker_pattern.i: src/textures/checker_pattern.c.i

.PHONY : src/textures/checker_pattern.i

# target to preprocess a source file
src/textures/checker_pattern.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/checker_pattern.c.i
.PHONY : src/textures/checker_pattern.c.i

src/textures/checker_pattern.s: src/textures/checker_pattern.c.s

.PHONY : src/textures/checker_pattern.s

# target to generate assembly for a file
src/textures/checker_pattern.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/checker_pattern.c.s
.PHONY : src/textures/checker_pattern.c.s

src/textures/perlin.o: src/textures/perlin.c.o

.PHONY : src/textures/perlin.o

# target to build an object file
src/textures/perlin.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/perlin.c.o
.PHONY : src/textures/perlin.c.o

src/textures/perlin.i: src/textures/perlin.c.i

.PHONY : src/textures/perlin.i

# target to preprocess a source file
src/textures/perlin.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/perlin.c.i
.PHONY : src/textures/perlin.c.i

src/textures/perlin.s: src/textures/perlin.c.s

.PHONY : src/textures/perlin.s

# target to generate assembly for a file
src/textures/perlin.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/perlin.c.s
.PHONY : src/textures/perlin.c.s

src/textures/solid_colour.o: src/textures/solid_colour.c.o

.PHONY : src/textures/solid_colour.o

# target to build an object file
src/textures/solid_colour.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/solid_colour.c.o
.PHONY : src/textures/solid_colour.c.o

src/textures/solid_colour.i: src/textures/solid_colour.c.i

.PHONY : src/textures/solid_colour.i

# target to preprocess a source file
src/textures/solid_colour.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/solid_colour.c.i
.PHONY : src/textures/solid_colour.c.i

src/textures/solid_colour.s: src/textures/solid_colour.c.s

.PHONY : src/textures/solid_colour.s

# target to generate assembly for a file
src/textures/solid_colour.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/solid_colour.c.s
.PHONY : src/textures/solid_colour.c.s

src/textures/texture.o: src/textures/texture.c.o

.PHONY : src/textures/texture.o

# target to build an object file
src/textures/texture.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/texture.c.o
.PHONY : src/textures/texture.c.o

src/textures/texture.i: src/textures/texture.c.i

.PHONY : src/textures/texture.i

# target to preprocess a source file
src/textures/texture.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/texture.c.i
.PHONY : src/textures/texture.c.i

src/textures/texture.s: src/textures/texture.c.s

.PHONY : src/textures/texture.s

# target to generate assembly for a file
src/textures/texture.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/textures/texture.c.s
.PHONY : src/textures/texture.c.s

src/threads/thread_pool.o: src/threads/thread_pool.c.o

.PHONY : src/threads/thread_pool.o

# target to build an object file
src/threads/thread_pool.c.o:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/threads/thread_pool.c.o
.PHONY : src/threads/thread_pool.c.o

src/threads/thread_pool.i: src/threads/thread_pool.c.i

.PHONY : src/threads/thread_pool.i

# target to preprocess a source file
src/threads/thread_pool.c.i:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/threads/thread_pool.c.i
.PHONY : src/threads/thread_pool.c.i

src/threads/thread_pool.s: src/threads/thread_pool.c.s

.PHONY : src/threads/thread_pool.s

# target to generate assembly for a file
src/threads/thread_pool.c.s:
	$(MAKE) -f CMakeFiles/miniRT.dir/build.make CMakeFiles/miniRT.dir/src/threads/thread_pool.c.s
.PHONY : src/threads/thread_pool.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... miniRT"
	@echo "... ft"
	@echo "... mlx42"
	@echo "... get_next_line"
	@echo "... src/image_save.o"
	@echo "... src/image_save.i"
	@echo "... src/image_save.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/render/aabb.o"
	@echo "... src/render/aabb.i"
	@echo "... src/render/aabb.s"
	@echo "... src/render/box.o"
	@echo "... src/render/box.i"
	@echo "... src/render/box.s"
	@echo "... src/render/bvh.o"
	@echo "... src/render/bvh.i"
	@echo "... src/render/bvh.s"
	@echo "... src/render/color.o"
	@echo "... src/render/color.i"
	@echo "... src/render/color.s"
	@echo "... src/render/constant_medium.o"
	@echo "... src/render/constant_medium.i"
	@echo "... src/render/constant_medium.s"
	@echo "... src/render/hit_record.o"
	@echo "... src/render/hit_record.i"
	@echo "... src/render/hit_record.s"
	@echo "... src/render/hittable.o"
	@echo "... src/render/hittable.i"
	@echo "... src/render/hittable.s"
	@echo "... src/render/hittable_list.o"
	@echo "... src/render/hittable_list.i"
	@echo "... src/render/hittable_list.s"
	@echo "... src/render/instance.o"
	@echo "... src/render/instance.i"
	@echo "... src/render/instance.s"
	@echo "... src/render/material.o"
	@echo "... src/render/material.i"
	@echo "... src/render/material.s"
	@echo "... src/render/material_dielectric.o"
	@echo "... src/render/material_dielectric.i"
	@echo "... src/render/material_dielectric.s"
	@echo "... src/render/material_diffuse_light.o"
	@echo "... src/render/material_diffuse_light.i"
	@echo "... src/render/material_diffuse_light.s"
	@echo "... src/render/material_isotropic.o"
	@echo "... src/render/material_isotropic.i"
	@echo "... src/render/material_isotropic.s"
	@echo "... src/render/material_lambertian.o"
	@echo "... src/render/material_lambertian.i"
	@echo "... src/render/material_lambertian.s"
	@echo "... src/render/material_metal.o"
	@echo "... src/render/material_metal.i"
	@echo "... src/render/material_metal.s"
	@echo "... src/render/matrix3.o"
	@echo "... src/render/matrix3.i"
	@echo "... src/render/matrix3.s"
	@echo "... src/render/moving_sphere.o"
	@echo "... src/render/moving_sphere.i"
	@echo "... src/render/moving_sphere.s"
	@echo "... src/render/quad.o"
	@echo "... src/render/quad.i"
	@echo "... src/render/quad.s"
	@echo "... src/render/sphere.o"
	@echo "... src/render/sphere.i"
	@echo "... src/render/sphere.s"
	@echo "... src/render_context.o"
	@echo "... src/render_context.i"
	@echo "... src/render_context.s"
	@echo "... src/scenes.o"
	@echo "... src/scenes.i"
	@echo "... src/scenes.s"
	@echo "... src/textures/checker_pattern.o"
	@echo "... src/textures/checker_pattern.i"
	@echo "... src/textures/checker_pattern.s"
	@echo "... src/textures/perlin.o"
	@echo "... src/textures/perlin.i"
	@echo "... src/textures/perlin.s"
	@echo "... src/textures/solid_colour.o"
	@echo "... src/textures/solid_colour.i"
	@echo "... src/textures/solid_colour.s"
	@echo "... src/textures/texture.o"
	@echo "... src/textures/texture.i"
	@echo "... src/textures/texture.s"
	@echo "... src/threads/thread_pool.o"
	@echo "... src/threads/thread_pool.i"
	@echo "... src/threads/thread_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

